Refactor annotation module and handle if enable_bounding_box turns on
choosehappy/HistoQC pull request #234
Opened 2023-02-03 22:38 UTC by nanli-emory

1. fixing the numerical precision in 'BaseImage'
2. refactoring the existing 'AnnotationModule'
3. deal with the bounding box in 'AnnotationModule'

2023-02-06 13:52 UTC, choosehappy requested changes

2023-02-06 13:52 UTC, choosehappy commented on histoqc/BaseImage.py
> +                if np.isclose(relative_down, 1, atol=.01): #there exists an open slide level exactly for this requested mag
A thought for you, perhaps "getBestLevelForDownsample" should return a binary flag as well to indicate if the level proposed is an existing openslide level?

in which case, this if statement would check the value of that boolean variable, instead of essentially doing the same computation again?

2023-02-06 13:52 UTC, choosehappy commented on histoqc/AnnotationModule.py
> +        s["warnings"].append(msg)
its not immediately clear to me how this code works? if format is None, where is it set so that the default becomes XML?

2023-02-06 13:52 UTC, choosehappy commented on histoqc/AnnotationModule.py
> +        file_path = s["dir"]
note here that file_path is set, but in the above if statement format is not set?

2023-02-08 21:33 UTC, nanli-emory commented on histoqc/AnnotationModule.py
> +        s["warnings"].append(msg)
Yes, you are right. set 'xml' as default.

2023-02-23 02:28 UTC, nanli-emory commented on histoqc/BaseImage.py
> +                if np.isclose(relative_down, 1, atol=.01): #there exists an open slide level exactly for this requested mag
Hi @choosehappy, I added a flag to indicate if the level proposed is an existing openslide level.
Also, merged the PR 236 code into BaseImage to fix the incorrect size output.

2023-02-27 17:35 UTC, choosehappy requested changes

2023-02-27 17:35 UTC, choosehappy commented on histoqc/BaseImage.py
> +    # this approach sequentially loads smaller tiles, resizes them, and then merges them together,
i think this comment was accidently still leftin place?

2023-02-27 17:35 UTC, choosehappy commented on histoqc/BaseImage.py
> +                # recommand having the dimension is less than 10k
recommend : )

2023-02-27 17:35 UTC, choosehappy commented on histoqc/BaseImage.py
> +        row_piece = np.concatenate(row_piece, axis=0)
can you adda comment here to note that this isn't very efficient, and if more efficiency isneeded we should likely refactor using "paste" from Image. or even just set the pixels directly with indexing?

2023-02-27 18:02 UTC, merged